export const taskConstants = {
  MOVE_FROM_COMPLETE_TO_PROGRESS: 'MOVE_FROM_COMPLETE_TO_PROGRESS',
  MOVE_FROM_COMPLETE_TO_NEXTUP: 'MOVE_FROM_COMPLETE_TO_NEXTUP',
  MOVE_FROM_NEXTUP_TO_PROGRESS: 'MOVE_FROM_NEXTUP_TO_PROGRESS',
  MOVE_FROM_NEXTUP_TO_COMPLETE: 'MOVE_FROM_NEXTUP_TO_COMPLETE',
  MOVE_FROM_PROGRESS_TO_NEXTUP: 'MOVE_FROM_PROGRESS_TO_NEXTUP',
  MOVE_FROM_PROGRESS_TO_COMPLETE: 'MOVE_FROM_PROGRESS_TO_COMPLETE',
};
export const chatConstants = {
  NEW_MSG: 'NEW_MSG',
};
